services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: next-app
    ports:
      - '3001:3000'
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true # ローカルのコンテナ内でホットリロードを実行するため
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    tty: true
    stdin_open: true

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      # 設定ファイルディレクトリにマウントする
      - ./mysql/conf.d:/etc/mysql/conf.d
      # DB初期化ディレクトリにマウントする
      # - ./mysql/init.d:/docker-entrypoint-initdb.d
    # ネットワーク
    networks:
      - default

networks:
  default:
    driver: bridge
