services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    ports:
      - '3001:3000'
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true # ローカルのコンテナ内でホットリロードを実行するため
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    tty: true
    stdin_open: true
    networks:
      - default
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: Asia/Tokyo
    volumes:
      # 設定ファイルディレクトリにマウントする
      - ./mysql/conf.d:/etc/mysql/conf.d
      # DB初期化ディレクトリにマウントする
      - ./mysql/init.d:/docker-entrypoint-initdb.d
      # dataのボリュームマウント
      - ./mysql/data:/var/lib/mysql
    # ネットワーク
    networks:
      - default

networks:
  default:
    driver: bridge
